namespace Senator.As400.Cloud.Sync.Application.Enums;
public enum TableType {
    CancellationPolicyLine,
    Client,
    ClientType,
    Contract,
    Extra,
    ExtraTranslation,
    Hotel,
    HotelRoomConfiguration,
    HotelSeason,
    Inventory,
    Language,
    Market,
    MinimumStay,
    Regime,
    OccupancyRate,
    OfferAndSupplement,
    OfferAndSupplementTranslation,
    OfferAndSupplementConfigurationPax,
    OfferAndSupplementGroup,
    OfferAndSupplementGroupOfferAndSupplement,
    PaymentType,
    PeriodPricing,
    PeriodPricingPax,
    Room,
    Tax
}
