namespace Senator.As400.Cloud.Sync.Infrastructure.Dtos.As400;
public class Conextra {
    public required string Id { get; set; } 
    public required string Fechamodi { get; set; } 
    public required string Code { get; set; } 
    public required string OriginCode { get; set; } 
    public required string OriginType { get; set; }
    public required int C5fred { get; set; }
    public required int C5freh { get; set; }
    public required int C5fec1 { get; set; }
    public required int C5fec2 { get; set; }
    public required int C5died { get; set; }
    public required int C5dieh { get; set; }
    public required string C5Sele { get; set; } 
    public required int C5unid { get; set; }
    public required int C5inta { get; set; }
    public required string C5foun { get; set; } 
    public required decimal C5prec { get; set; }
    public required string C5form { get; set; } 
    public required string C5apdt { get; set; } 
    public required int C5cocu { get; set; }
    public required decimal C5dtn1 { get; set; }
    public required decimal C5dtn2 { get; set; }
    public required decimal C5dtn3 { get; set; }
    public required decimal C5dtn4 { get; set; }
    public required decimal C5dta1 { get; set; }
    public required decimal C5dta2 { get; set; }
    public required decimal C5dta3 { get; set; }
    public required decimal C5dta4 { get; set; }
    public required string C5th01 { get; set; } 
    public required string C5th02 { get; set; } 
    public required string C5th03 { get; set; } 
    public required string C5th04 { get; set; } 
    public required string C5th05 { get; set; } 
    public required string C5th06 { get; set; } 
    public required string C5th07 { get; set; } 
    public required string C5th08 { get; set; } 
    public required string C5th09 { get; set; } 
    public required string C5th10 { get; set; } 
    public required string C5th11 { get; set; } 
    public required string C5th12 { get; set; } 
    public required string C5th13 { get; set; } 
    public required string C5th14 { get; set; } 
    public required string C5th15 { get; set; } 
    public required string C5reg1 { get; set; } 
    public required string C5reg2 { get; set; } 
    public required string C5reg3 { get; set; } 
    public required string C5reg4 { get; set; } 
    public required string C5reg5 { get; set; } 
    public required string Offoe { get; set; } 
    public required bool IsCommissionable { get; set; }
    public required bool TaxesIncluded { get; set; }
}
