name: Ejecutar comando ping y guardar registros

on:
  push:
    branches: [main]
    
jobs:
  ping_job:
    runs-on: [self-hosted, Linux, X64, docker, build]
    steps:
      - name: Ejecutar ping a example.com y guardar registros
        run: |
          ping -c 4 google.com > ping_output.txt
      - name: Subir registros como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: ping-logs
          path: ping_output.txt
